name: flutter_siin_shop
description: Siin Shop | A Video E-Commerce.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# app version
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies that my app needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.2
  animated_notch_bottom_bar:
    git: https://github.com/NaimurDev/flutter_animated_notch_bottom_bar
  # dependency injection
  get_it: ^7.6.0
  # network
  dio: ^5.2.0+1
  # sate management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # route
  go_router: ^9.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints"
  flutter_lints: ^2.0.0
  # change app icon
  flutter_launcher_icons: ^0.13.1

# app icon config
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"

# for
flutter:

  # use material
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
